[project]
name = "product-info-backend"
version = "0.1.0"
description = "A backend service for managing product information."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.5",
    "djangorestframework>=3.16.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pytest>=8.4.1",
    "pytest-bdd>=8.1.0",
    "pytest-cov>=6.2.1",
    "pytest-django>=4.11.1",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
]
