"""Django settings for mercadolibre_api project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGO_SECRET_KEY=(
        str,
        "django-insecure-_&&rk%#ees%vmp$6pm@v_v8(f^_=7rn*2@wjck)%mj6t6%%mwb",
    ),
    DJANGO_ALLOWED_HOSTS=(list, "0.0.0.0,localhost,127.0.0.1,[::1]".split(",")),
    DJANGO_DB_ATOMIC_REQUESTS=(bool, False),
    DJANGO_CONN_MAX_AGE=(int, 0),
    DJANGO_STATIC_ROOT=(str, ""),
    DJANGO_STATIC_URL=(str, "static/"),
    DJANGO_LOG_LEVEL=(str, "INFO"),
    DJANGO_SECURE_CONTENT_TYPE_NOSNIFF=(bool, True),
    DJANGO_SECURE_BROWSER_XSS_FILTER=bool,
    DJANGO_SECURE_SSL_REDIRECT=bool,
    DJANGO_CSRF_COOKIE_SECURE=bool,
    DJANGO_SESSION_COOKIE_SECURE=bool,
    DJANGO_SESSION_COOKIE_HTTPONLY=bool,
    DJANGO_LANGUAGE_COOKIE_SECURE=bool,
    DJANGO_LANGUAGE_COOKIE_HTTPONLY=bool,
    LANGUAGE_COOKIE_NAME=(str, "django_language"),
    IMAGE_TAG=(str, ""),
    COMMIT_TAG=(str, ""),
    DJANGO_CSRF_TRUSTED_ORIGINS=(list, ["https://*.some_host.com"]),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# Override with env settings for different deploy types
env_path_default = BASE_DIR / ".." / ".env"

if env_path_default.exists():
    environ.Env.read_env(env_path_default)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG")
ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS")
# TODO: document this
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Application definition

INSTALLED_APPS = [
    "modeltranslation",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mercadolibre_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mercadolibre_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

MODELTRANSLATION_DEFAULT_LANGUAGE = "pt-br"
MODELTRANSLATION_FALLBACK_LANGUAGES = ("pt-br", "en")
MODELTRANSLATION_AUTO_POPULATE = True
MODELTRANSLATION_ENABLE_FALLBACKS = True


def gettext(s: str) -> str:
    """Return the same string it received.

    This is a dummy gettext function, as Django expects it.
    """
    return s


LANGUAGES = (
    ("pt-br", gettext("Brazilian Portuguese")),
    ("en", gettext("English")),
)


TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = env("DJANGO_STATIC_URL")
STATIC_ROOT = BASE_DIR / "staticfiles"
if env("DJANGO_STATIC_ROOT"):
    STATIC_ROOT = env("DJANGO_STATIC_ROOT")


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# TODO: document this
SECURE_CONTENT_TYPE_NOSNIFF = env("DJANGO_SECURE_CONTENT_TYPE_NOSNIFF", default=True)
USE_X_FORWARDED_HOST = env("DJANGO_USE_X_FORWARDED_HOST", default=True)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTOCOL", "https")
SECURE_BROWSER_XSS_FILTER = env("DJANGO_SECURE_BROWSER_XSS_FILTER", default=not DEBUG)

SECURE_SSL_REDIRECT = env("DJANGO_SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env("DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = env("DJANGO_SESSION_COOKIE_HTTPONLY", default=not DEBUG)

if env("DJANGO_CSRF_TRUSTED_ORIGINS"):
    CSRF_TRUSTED_ORIGINS = env("DJANGO_CSRF_TRUSTED_ORIGINS")
CSRF_COOKIE_SECURE = env("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SAMESITE = "Strict"
CSRF_COOKIE_HTTPONLY = False

LANGUAGE_COOKIE_NAME = env("LANGUAGE_COOKIE_NAME").replace(" ", "")
if not LANGUAGE_COOKIE_NAME:
    LANGUAGE_COOKIE_NAME = "django_language"

LANGUAGE_COOKIE_SAMESITE = "Strict"


SECURE_CROSS_ORIGIN_OPENER_POLICY = None

LANGUAGE_COOKIE_SECURE = env("DJANGO_LANGUAGE_COOKIE_SECURE", default=not DEBUG)
LANGUAGE_COOKIE_HTTPONLY = env("DJANGO_LANGUAGE_COOKIE_HTTPONLY", default=False)

if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
