name: Django CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install Dependencies
      run: uv install

      # TODO: change this to run pre-commit + coverage
    - name: Run Code Quality Checks (Ruff & Bandit)
      run: |
        ruff check src
        bandit -r src

    - name: Run Tests with Pytest
      run: |
        pytest
