name: Django CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        uv pip install .

    - name: Run pre-commit hooks
      run: |
        source .venv/bin/activate
        pre-commit run --all-files

    - name: Run Tests with Coverage
      run: |
        source .venv/bin/activate
        pytest --cov=src --cov-fail-under=80
